name: CustomName
version: '${project.version}'
main: mrzitrrone.CustomNamePlugin
api-version: '1.21'
folia-supported: true
author: MrZitrrone
description: Custom Names & Prefixe mit vollem MiniMessage Support
softdepend: [PlaceholderAPI]

commands:
  customname:
    description: Ändere deinen angezeigten Namen
    usage: /customname [MiniMessage Format]
    aliases: [cn, nickname]
  prefix:
    description: Setze dein Prefix (MiniMessage)
    usage: /prefix <MiniMessage> | /prefix reset | /prefix set <Spieler> <Prefix>
    aliases: [cnprefix, tag]

permissions:
  customname.use:
    description: Erlaubt das Ändern der eigenen Namensfarbe
    default: false
  customname.nick:
    description: Erlaubt das Ändern des kompletten Namens (Nick)
    default: false
  customname.prefix.use:
    description: Erlaubt das Setzen eines eigenen Prefixes
    default: false
  customname.prefix.others:
    description: Erlaubt das Setzen von Prefixen anderer Spieler
    default: op
  customname.color.rainbow:
    description: Zugriff auf die Regenbogen-Farbe im GUI
    default: op
  customname.admin:
    description: Admin Berechtigung
    default: op
  customname.bypass.prefix:
    description: Umgeht das Nick-Prefix
    default: false
